name: 发布到阿里云轻量

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build-production:
    runs-on: ubuntu-latest

    steps: # 自动化步骤
      - uses: actions/checkout@master # 第一步，检出仓库副本

      - name: 发布到服务器并重启服务
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_PORT: "22"
          REMOTE_HOST: 47.238.180.18
          REMOTE_USER: root
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "/"
          TARGET: /wwwroot/material_edit
          EXCLUDE: "/.git/,/.github/,/.vscode/"

          SCRIPT_AFTER: |
            cd /wwwroot/material_edit
            npm install
            npm run build
            
